### PR TITLE
Bumping version to 2.1.0 from the work by @mwpastore

### PR DESCRIPTION
**Pull request by jonathanKingston**

### CODE REVIEW

**Comment by jonathanKingston** [comment]
@mwpastore npm published also, let me know if there are any issues. Thanks again!

**Comment by mwpastore** [comment]
@jonathanKingston Awesome! Thanks for everything. I've been running my forks in production for the past few days so I'm feeling pretty confident in the full solution. Are you comfortable with me making a quick announcement on the EmberJS Community Slack or is that something you'd like to do?

**Comment by jonathanKingston** [comment]
Nope you own the credit! (I shamefully am actually too busy to check this in Ember even - I will check tonight anyway)

**Comment by mwpastore** [comment]
You are too humble! Thank you. I just think this is a great add-on and perfectly demonstrates the power of Ember.js and its ecosystem, so I'm happy I was able to contribute in some small way.

**Pull request merged**
