### PR TITLE
Add fingerprintCheck option and documentation

### PR DESCRIPTION
**Pull request by mwpastore**
Final fixes for issue #20!

### CODE REVIEW

**Comment by mwpastore** [comment]
Hrrm, does that normally happen?

**Comment by jonathanKingston** [comment]
Nope, I think it has before. Could you try committing like a line change or something that does a change without causing linting issues and push -f?

**Comment by mwpastore** [comment]
Hi Jonathan, I had a quick chat with @rwjblue. He pointed me to [this](http://emberjs.com/blog/2016/01/15/ember-2-3-released.html#toc_removing-the-jquery-version-assertion) blog post and suggested we either bump the default Ember version or lock the jQuery version. I took the latter approach and it looks like that did the trick!

**Comment by mwpastore** [comment]
Hi @jonathanKingston, just a friendly poke/prod that this is ready to go, as far as I know. :smiley: Thank you in advance!

**Comment by jonathanKingston** [comment]
Sounds good enough for me if it is good enough for @rwjblue.
I left the options out of `ember-cli-sri` as I figured it was already complex enough however that isn't a blocker and I probably was wrong. At the time of development SRI was still being standardised so I thought it was best not to confuse people.
Thanks!

**Comment by mwpastore** [comment]
Thank you!

**Pull request merged**
